### ISSUE TITLE
Syslog report message

### ISSUE THREAD

**Issue by rchen14b** [Cacti/plugin_syslog#40] opened 2018-01-17 15:14 UTC
Hey Guys,

We are using newest version. But the report only show Date and Message of that syslog. Is there anyway it can display host name and program?

**Comment by David-yanp** [comment] 2018-02-12 08:07
Maybe this link can help you [rsyslog Templates](http://www.rsyslog.com/doc/v8-stable/configuration/templates.html)

**Comment by rchen14b** [comment] 2018-02-13 15:21
@itsjoke Hey David,
Thanks for your comment. Since the cacti already have a syslog template, I feel like this alert is only displaying message part and ignored device and program. Is that right?

**Comment by jpobeda** [comment] 2018-02-20 02:20
You're right I'm also looking forward to have at the very least 'hostname' included in reports.

Maybe @cigamit or @netniV can easly get that in.

**Comment by netniV** [comment] 2018-02-20 07:32
I've never even attempted to use this plugin, not even sure at this time in the morning what it does besides some magic around syslog messages... either going in or coming out... maybe... 🐳

**Comment by David-yanp** [comment] 2018-02-22 01:23
@rchen29 My hostname and program is normal.
![image](https://user-images.githubusercontent.com/11266502/36514919-f81c8db4-17b1-11e8-974e-4b7aac2afd34.png)

**Comment by jpobeda** [comment] 2018-02-22 01:43
@itsjoke you got it wrong. The problem is when you get the report emailed.

![image](https://user-images.githubusercontent.com/13456559/36515525-b02aa73e-17de-11e8-9b33-66a77f521d76.png)

**Comment by David-yanp** [comment] 2018-02-23 04:32
my mistake :sweat:

**Comment by rchen14b** [comment] 2018-03-27 16:09
Thanks. @jpobeda @cigamit 
I have updated our cacti syslog today. Will updated result back tomorrow morning. BTW, is there a way to manually send a syslog report?

**Comment by jpobeda** [comment] 2018-03-27 19:30
@rchen29 , yes, you can do 
`cd /usr/share/cacti/plugins/syslog` -> or whatever is your cacti's path
`php -q syslog_process.php --debug --force-report`

**Comment by rchen14b** [comment] 2018-03-27 21:06
Hey @jpobeda 
Thanks for your reply. I tried this command and it got stucked somewhere when I run this command.
![image](https://user-images.githubusercontent.com/13096569/37994989-c62be962-31d8-11e8-8eda-028406bd0d00.png)
Any idea?

**Comment by jpobeda** [comment] 2018-03-27 21:24
Well, that's weird...you got stucked right after..
@rchen29 Have you kept your config.php? If you've just upgraded it maybe you forgot to put that back, maybe?.. mm

**Comment by jpobeda** [comment] 2018-03-27 21:30
This is how mine looks

> php -q syslog_process.php --debug --force-report
> SYSLOG: Syslog Table IS Partitioned
> SYSLOG: Unique ID = 72
> SYSLOG: Found   0, New Message(s) to process
> SYSLOG: Found   7,  Removal Rule(s) to process
> SYSLOG: Deleted 0,  Messages for removal rule 'Remove AUTHMGR-5-FAIL msgs'
> SYSLOG: Deleted 1,  Message for removal rule 'Remove xntpd-6-INFO msgs'
> SYSLOG: Deleted 2,  Message for removal rule 'Remove STKUNIT0-M:CP %NTP-6-STRATUM msgs'
> SYSLOG: Deleted 2,  Messages for removal rule 'Remove AUTHMGR-5-START msgs'
> SYSLOG: Deleted 2,  Messages for removal rule 'Remove PARSER-5-CFGLOG_LOGGEDCMD msgs'
> SYSLOG: Deleted 2,  Messages for removal rule 'Remove AUTHMGR-5-SUCCESS msgs'
> SYSLOG: Deleted 2,  Messages for removal rule 'Remove SWITCH_QOS_TB msgs'
> SYSLOG: Found   20,  Alert Rules to process
> SYSLOG: Moved   0,  Message(s) to the 'syslog' table
> SYSLOG: Deleted 0,  Already Processed Message(s) from incoming
> SYSLOG: Deleted 0,  Syslog alarm log Record(s)
> SYSLOG: Deleted 0,  Syslog Host Record(s)
> SYSLOG: Deleted 0,  Syslog Host/Facility Record(s)
> SYSLOG: Deleted 0,  Old programs from programs table
> SYSLOG: Processing Reports...
> SYSLOG: We have 4 Reports in the database
>    Report: Radius dead Report
>        Next Send: Now
>        Creating Report...
> SYSLOG: We have 2 items for the Report
> SYSLOG: Sending Alert email to 'mail@domain.com'
>    Report: LOGIN FAILURE Report
>        Next Send: Now
>        Creating Report...
> SYSLOG: We have 2 items for the Report
> SYSLOG: Sending Alert email to 'mail@domain.com'
>    Report: devicer1
>        Next Send: Now
>        Creating Report...
> SYSLOG: We have 0 items for the Report
>    Report: Cisco MAC Flap Report
>        Next Send: Now
>        Creating Report...
> SYSLOG: We have 31 items for the Report
> SYSLOG: Sending Alert email to 'mail@domain.com'
> SYSLOG: Finished processing Reports...
> 28/Mar/2018 10:22:20 - SYSTEM SYSLOG STATS:Time:0.81 Deletes:0 Incoming:0 Removes:2 XFers:0 Alerts:20 Alarms:0 Reports:4

**Comment by jpobeda** [comment] 2018-03-27 22:23
I think I found what was the issue for you. I made the changes on my install but committed the wrong changes :/

My bad..I made the changes on my fork now, if you want to test before @cigamit commits it.

https://github.com/jpobeda/plugin_syslog/tree/jpobeda-patch-1

**Comment by jpobeda** [comment] 2018-03-28 00:15
@rchen29 , @netniV has been committed the changes, give it a go and let me know how it goes.

**Comment by rchen14b** [comment] 2018-03-28 01:45
@jpobeda Thanks. It looks like my syslog had an issue with the database. I was convert syslog from MyISAM to Innodb and then it had this error.
<img width="1432" alt="screen shot 2018-03-27 at 8 40 51 pm" src="https://user-images.githubusercontent.com/13096569/38003937-780dfc08-31ff-11e8-9ee4-bb581ecc1ea4.png">
But it was took like 60s before I update the syslog, now it took forever to run it. When I try to send a report, it stuck at:
[root@customers syslog]# php -q syslog_process.php --debug --force-report
SYSLOG: Syslog Table IS Partitioned
SYSLOG: Unique ID = 117
SYSLOG: Found   26, New Message(s) to process
SYSLOG: Found   18,  Removal Rule(s) to process
SYSLOG: Deleted 0,  Messages for removal rule 'Customer host block'
SYSLOG: Deleted 0,  Messages for removal rule '400L MAC Block'
SYSLOG: Deleted 0,  Messages for removal rule '950L MAC Block'
SYSLOG: Deleted 0,  Messages for removal rule '1333W MAC Block'
SYSLOG: Deleted 0,  Messages for removal rule '221 Hubbard'
SYSLOG: Deleted 0,  Messages for removal rule 'Radio log removal'
SYSLOG: Deleted 0,  Messages for removal rule 'New Removal Record'
SYSLOG: Deleted 0,  Messages for removal rule '1743L MAC removal'
SYSLOG: Deleted 1,  Message for removal rule '1333W Removal'
SYSLOG: Deleted 1,  Messages for removal rule '939M Deletion'
SYSLOG: Deleted 1,  Messages for removal rule '1000L Deletion2'
SYSLOG: Deleted 1,  Messages for removal rule '520S Deletion'
SYSLOG: Deleted 1,  Messages for removal rule 'Daemon Delection'
SYSLOG: Deleted 1,  Messages for removal rule '30B Deletion'
SYSLOG: Deleted 1,  Messages for removal rule '353C.d1 remove1'
SYSLOG: Deleted 1,  Messages for removal rule '353C.d1 remove2'
SYSLOG: Deleted 8,  Messages for removal rule '333brendan408'
SYSLOG: Deleted 8,  Messages for removal rule '5009S removal1'
SYSLOG: Found   0,  Alert Rules to process
SYSLOG: Moved   18,  Message(s) to the 'syslog' table
SYSLOG: Deleted 18,  Already Processed Message(s) from incoming
SYSLOG: Deleted 0,  Syslog alarm log Record(s)
SYSLOG: Deleted 38,  Syslog Host Record(s)
SYSLOG: Deleted 0,  Syslog Host/Facility Record(s)

Any suggestion? Should I reinstall syslog plugin? Am I able to save the old syslog if I need completely rebuilt the database? 
Thanks

**Comment by jpobeda** [comment] 2018-03-28 02:10
So every time you upgrade your syslog plugin, you're replacing the whole folder or every file with the new version you've downloaded. If you are doing that, you should go again and edit config.php file. That's the file where you tell if syslog db is within cacti's db or completely separated database and it's name, username, password, etc.

@rchen29 , Can you please clarify if your syslog db is a standalone database or part of cacti's one?

**Comment by rchen14b** [comment] 2018-03-28 02:15
@jpobeda 
I think my upgrade is fine. Every time I replace whole folder, I copy back the old config.php. 

I'm using a standalone database. I was using MyISAM type of database, but the syslog had really low performance so I converted database to Innodb. After that, it had the db error. But the syslog process time was around 60s.

After I upgraded syslog today, it had a insane process time.

**Comment by jpobeda** [comment] 2018-03-28 03:41
that's odd , I had that performance issue when I first tried it and it was due to "Enable Statistics Gathering".

I also converted the database and at the end I ended up re-installing it and using cacti's database and InnoDB. I was also having issues when using standalone syslog db.

I've downloaded the develop branch and tested it myself and it worked for me.

You could go to the version prior to my commits 
https://github.com/Cacti/plugin_syslog/tree/a5dc43613ae2ebb1b00b958ac27e80bffc330fc5


Just to clarify my mind, did you get that issue after or before my patch?

I've only touched 3 SQL queries, syslog.css and html table for the reports, nothing to do with the core process and as I said, I'm running this exactly version.

**Comment by netniV** [comment] 2018-03-28 08:14
If you put the plugin into debug mode (via the Console -> Configuration -> Settings), can you post the results of the logs from that?  This almost sounds like an indexing problem or something like that.  One thing you may want to do is temporarily disable the crontab and then manual try some selects against the tables.  If these are taking too long, changes are the connection is being closed for idleness.

**Comment by rchen14b** [comment] 2018-03-28 14:18
Hey @jpobeda @netniV , thanks for the quick response and help. Here are the debug logs:

2018/03/28 09:16:43 - DBCALL DEVEL: SQL Exec: "DELETE FROM `syslog`.`syslog_programs` WHERE program_id NOT IN(SELECT DISTINCT program_id FROM `syslog`.`syslog` UNION SELECT DISTINCT program_id FROM syslog_removed)"
2018/03/28 09:16:43 - DBCALL DEVEL: SQL Exec: "DELETE FROM `syslog`.`syslog_host_facilities` WHERE last_updated<'2017-03-28 09:16:43'"
2018/03/28 09:16:43 - DBCALL DEVEL: SQL Exec: "DELETE FROM `syslog`.`syslog_programs` WHERE last_updated<'2017-03-28 09:16:43'"
2018/03/28 09:16:43 - DBCALL DEVEL: SQL Exec: "DELETE FROM `syslog`.`syslog_hosts` WHERE last_updated<'2017-03-28 09:16:43'"
2018/03/28 09:16:43 - DBCALL DEVEL: SQL Exec: "DELETE FROM `syslog`.`syslog_logs` WHERE logtime<'2017-03-28 09:16:43'"
2018/03/28 09:16:43 - DBCALL DEVEL: SQL Assoc: "SELECT ph.name, ph.file, ph.function FROM plugin_hooks AS ph LEFT JOIN plugin_config AS pc ON pc.directory = ph.name WHERE ph.status = 1 AND hook = ? ORDER BY pc.id ASC"
2018/03/28 09:16:43 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_hooks'"
2018/03/28 09:16:43 - DBCALL DEVEL: SQL Exec: "TRUNCATE `syslog`.`syslog_statistics`"
2018/03/28 09:16:43 - DBCALL DEVEL: SQL Exec: "DELETE FROM `syslog`.`syslog_incoming` WHERE status=72"
2018/03/28 09:16:43 - DBCALL DEVEL: SQL Exec: "INSERT INTO `syslog`.`syslog` (logtime, priority_id, facility_id, program_id, host_id, message) SELECT TIMESTAMP(`date`, `time`), priority_id, facility_id, program_id, host_id, message FROM (SELECT date, time, priority_id, facility_id, program_id, host_id, message FROM syslog_incoming AS si INNER JOIN syslog_hosts AS sh ON sh.host=si.host INNER JOIN syslog_programs AS sp ON sp.program=si.program WHERE status=72) AS merge"
2018/03/28 09:16:43 - DBCALL DEVEL: SQL Assoc: "SELECT ph.name, ph.file, ph.function FROM plugin_hooks AS ph LEFT JOIN plugin_config AS pc ON pc.directory = ph.name WHERE ph.status = 1 AND hook = ? ORDER BY pc.id ASC"
2018/03/28 09:16:43 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_hooks'"
2018/03/28 09:16:43 - DBCALL DEVEL: SQL Assoc: "SELECT * FROM `syslog`.`syslog_alert` WHERE enabled='on'"
2018/03/28 09:16:43 - DBCALL DEVEL: SQL Exec: "DELETE FROM `syslog`.`syslog_incoming` WHERE host='localhost' AND status='72'"
2018/03/28 09:16:43 - DBCALL DEVEL: SQL Exec: "DELETE FROM `syslog`.`syslog_incoming` WHERE (program="hostapd") AND status='72'"
2018/03/28 09:16:43 - DBCALL DEVEL: SQL Exec: "DELETE FROM `syslog`.`syslog_incoming` WHERE (program="dropbear") AND status='72'"
2018/03/28 09:16:43 - DBCALL DEVEL: SQL Exec: "DELETE FROM `syslog`.`syslog_incoming` WHERE host='customers' AND status='72'"
2018/03/28 09:16:43 - DBCALL DEVEL: SQL Cell: "SELECT count(*) FROM `syslog`.`syslog_incoming` WHERE status=72"
2018/03/28 09:16:43 - DBCALL DEVEL: SQL Assoc: "SELECT * FROM `syslog`.`syslog_remove` WHERE enabled='on'"
2018/03/28 09:16:43 - DBCALL DEVEL: SQL Exec: "INSERT INTO `syslog`.`syslog_host_facilities` (host_id, facility_id) SELECT host_id, facility_id FROM ((SELECT DISTINCT host, facility_id FROM `syslog`.`syslog_incoming` WHERE status=72) AS s INNER JOIN `syslog`.`syslog_hosts` AS sh ON s.host=sh.host) ON DUPLICATE KEY UPDATE host_id=VALUES(host_id), last_updated=NOW()"
2018/03/28 09:16:43 - DBCALL DEVEL: SQL Exec: "INSERT INTO `syslog`.`syslog_hosts` (host) SELECT DISTINCT host FROM `syslog`.`syslog_incoming` WHERE status=72 ON DUPLICATE KEY UPDATE host=VALUES(host), last_updated=NOW()"
2018/03/28 09:16:43 - CMDPHP SQL Backtrace: (/plugins/syslog/syslog_process.php: 681 syslog_process_log)(/plugins/syslog/syslog_process.php: 692 db_execute)(/lib/database.php: 136 db_execute_prepared)(/lib/database.php: 209 cacti_debug_backtrace)
2018/03/28 09:16:43 - CMDPHP ERROR: A DB Exec Failed!, Error: MySQL server has gone away
2018/03/28 09:16:43 - DBCALL ERROR: A DB Exec Failed!, Error:2006, SQL:'REPLACE INTO `cacti`.`settings` SET name='syslog_stats', value='time:1114.62 deletes:0 incoming:204 removes:187 xfers:0 alerts:0 alarms:0 reports:1''
2018/03/28 09:16:43 - SYSTEM SYSLOG STATS:Time:1114.62 Deletes:0 Incoming:204 Removes:187 XFers:0 Alerts:0 Alarms:0 Reports:1
2018/03/28 09:16:11 - SYSTEM THOLD STATS: Time:0.3831 Tholds:468 TotalDevices:833 DownDevices:5 NewDownDevices:0
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Exec: "INSERT INTO `syslog`.`syslog_programs` (program) SELECT DISTINCT program FROM `syslog`.`syslog_incoming` WHERE status=72 ON DUPLICATE KEY UPDATE program=VALUES(program), last_updated=NOW()"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Assoc: "SELECT ph.name, ph.file, ph.function FROM plugin_hooks AS ph LEFT JOIN plugin_config AS pc ON pc.directory = ph.name WHERE ph.status = 1 AND hook = ? ORDER BY pc.id ASC"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_hooks'"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Exec: "UPDATE `syslog`.`syslog_incoming` SET status=72 WHERE status=0"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Cell: "SELECT count(*) FROM `syslog`.`syslog_incoming` WHERE status=72"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Cell: "SELECT PARTITION_NAME FROM `information_schema`.`partitions` WHERE table_schema='syslog' AND table_name='syslog' ORDER BY partition_ordinal_position DESC LIMIT 1,1"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Cell: "SELECT PARTITION_NAME FROM `information_schema`.`partitions` WHERE table_schema='syslog' AND table_name='syslog' ORDER BY partition_ordinal_position DESC LIMIT 1,1"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Row: "SHOW CREATE TABLE `syslog`.`syslog`"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Exec: "SET SESSION sql_mode = "NO_ENGINE_SUBSTITUTION""
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Cell: "SELECT @@sql_mode"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Assoc: "SELECT ph.name, ph.file, ph.function FROM plugin_hooks AS ph LEFT JOIN plugin_config AS pc ON pc.directory = ph.name WHERE ph.status = 1 AND hook = ? ORDER BY pc.id ASC"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_hooks'"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Assoc: "SELECT ph.name, ph.file, ph.function FROM plugin_hooks AS ph LEFT JOIN plugin_config AS pc ON pc.directory = ph.name WHERE ph.status = 1 AND hook = ? ORDER BY pc.id ASC"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_hooks'"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Cell: "SELECT id FROM data_source_profiles ORDER BY `default` DESC LIMIT 1"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'data_source_profiles'"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Assoc: "SELECT ph.name, ph.file, ph.function FROM plugin_hooks AS ph LEFT JOIN plugin_config AS pc ON pc.directory = ph.name WHERE ph.status = 1 AND hook = ? ORDER BY pc.id ASC"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_hooks'"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Assoc: "SELECT ph.name, ph.file, ph.function FROM plugin_hooks AS ph LEFT JOIN plugin_config AS pc ON pc.directory = ph.name WHERE ph.status = 1 AND hook = ? ORDER BY pc.id ASC"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_hooks'"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Assoc: "SELECT directory AS id, name FROM plugin_config WHERE status=1"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_config'"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Assoc: "SELECT DISTINCT gt.id, gt.name FROM graph_templates AS gt INNER JOIN graph_templates_item AS gti ON gt.id=gti.graph_template_id INNER JOIN data_template_rrd AS dtr ON gti.task_item_id=dtr.id WHERE gti.local_graph_id=0 AND data_source_type_id IN (3,2) ORDER BY name"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Assoc: "SELECT * FROM plugin_realms ORDER BY plugin, display"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Assoc: "SELECT ph.name, ph.file, ph.function FROM plugin_hooks AS ph LEFT JOIN plugin_config AS pc ON pc.directory = ph.name WHERE ph.status = 1 AND hook = ? ORDER BY pc.id ASC"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'plugin_hooks'"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Row: "SELECT value FROM settings_user WHERE name = ? AND user_id = ?"
2018/03/28 09:16:11 - DBCALL DEVEL: SQL Cell: "SHOW TABLES LIKE 'settings_user'"
2018-03-28 09:16:11 - DBCALL DEVEL: SQL Cell: "SELECT cacti FROM version LIMIT 1"
2018-03-28 09:16:11 - DBCALL DEVEL: SQL Exec: "SET SESSION sql_mode = "NO_ENGINE_SUBSTITUTION""
2018-03-28 09:16:11 - DBCALL DEVEL: SQL Cell: "SELECT @@sql_mode"

If its a indexing problem, can I reinstall syslog database? If I backup the syslog table to save my data, will I able to restore it to new database? We have a huge amount of syslog, so it might not be a good idea to fix the indexing.

**Comment by netniV** [comment] 2018-03-28 14:28
The MySQL error seems to occur almost immediately after the syslog.syslog_host insert statement which makes me think there is something going wrong with that.  Can you do a `SHOW CREATE TABLE  syslog.syslog_host_facilities\G` for the table listed above?  Then try and do a `SELECT * FROM  syslog.syslog_host_facilities` (only really interested in the time it takes for that one).

**Comment by rchen14b** [comment] 2018-03-28 14:54
Hey @netniV ,

Here is the information:

MariaDB [syslog]> SHOW CREATE TABLE syslog.syslog_host_facilities\G
*************************** 1. row ***************************
       Table: syslog_host_facilities
Create Table: CREATE TABLE `syslog_host_facilities` (
  `host_id` int(10) unsigned NOT NULL,
  `facility_id` int(10) unsigned NOT NULL,
  `last_updated` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`host_id`,`facility_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
1 row in set (0.000 sec)


MariaDB [syslog]> SELECT * FROM syslog.syslog_host_facilities
    -> ;
+---------+-------------+---------------------+
| host_id | facility_id | last_updated        |
.
.
.
.
+---------+-------------+---------------------+
301 rows in set (0.002 sec)

**Comment by netniV** [comment] 2018-03-28 15:04
So, there doesn't appear to be an issue there. Very strange.

**Comment by jpobeda** [comment] 2018-03-28 19:49
This seems to be a complete different issue. You mentioned before that you've got a huge amount of devices reporting to that syslog and sending lots of messages. Maybe you're blowing away your mysql instances. Is it cacti database running on the same box as well? noticed any performance issues on Cacti?

Nothing on /var/log/messages?

**Comment by rchen14b** [comment] 2018-03-29 14:11
@netniV @jpobeda 
Hey Guys,

Thanks so much for the help. It could be my syslog database is messed up. But I confirmed this morning that the syslog report work fine with the right Host, Date and Message. BTW, is that simple to also include program in the report?

**Comment by jpobeda** [comment] 2018-04-02 21:43
@rchen29 close this issue if you're happy with the hostname field on reports and please open a new one requesting the additional field. 
This issue has got way too messy.

**Closed as completed** 2018-04-02 22:07 UTC

**Comment by rchen14b** [comment] 2018-04-02 23:47
@jpobeda @netniV  Thanks for the help guys. I think the database one was a separate issue. The new report display work fine.
